_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
log_dir:
    value: runs\20250401_190526
sub_dir:
    value: null
